---
# - name: Install pip
#   become: yes
#   apt:
#     name: python3-pip
#     state: latest
#     update_cache: yes

# - name: Update pip
#   pip:
#     name: pip
#     state: latest
#     executable: pip3

- name: Install Openstack
  pip:
    name: openstacksdk
    state: latest
    executable: pip
