---
- name: Start Client
  docker_container:
    name: ccc_client_{{ ansible_hostname }}
    image: kvoli/ccc-client:latest
    state: started
    restart: yes
    ports:
    - "8000:5000"
    env:
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_passwd }}"
      NODE_ID: "{{ ansible_hostname }}"
      VIRTUAL_HOST: a.unimelb-comp90024-2020-grp-11.cloud.edu.au
      VIRTUAL_PORT: "8000"
      LETSENCRYPT_HOST: a.unimelb-comp90024-2020-grp-11.cloud.edu.au
      LETSENCRYPT_EMAIL: amcclernon@student.unimelb.edu.au
      http_proxy: http://wwwproxy.unimelb.edu.au:8000
      https_proxy: http://wwwproxy.unimelb.edu.au:8000
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000
      ftp_proxy: http://wwwproxy.unimelb.edu.au:8000
  become: yes
