---
- name: Gather facts
  setup:
    gather_subset: all

- name: Assert local proxy already configured.
  shell: grep "^http_proxy" /etc/environment
  register: test_proxy_exist
  failed_when: "test_proxy_exist.rc == 2"
  changed_when: false

- name: Configure proxy
  template:
    src: env.j2
    dest: /etc/environment
    force: true
  when: test_proxy_exist.rc == 1

- shell: cat /etc/environment
  register: env_content

- debug:
    var: env_content.stdout_lines

- name: Restart SSH service
  import_tasks: restart_ssh.yaml

- name: Configure instance timezone to Australia/Melbourne
  timezone:
    name: Australia/Melbourne

- name: Restart Cron service
  service:
    name: cron
    state: restarted

- name: Activate NTP service
  shell: timedatectl set-ntp on

- name: Install general packages
  apt:
    name:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "python-setuptools",
        "software-properties-common",
        "vim",
      ]
    state: latest
    update_cache: yes
    install_recommends: no

# Disabled as current image has Docker. Keeping this for the moment as
# pre-loaded image requires all Docker actions as sudo - may be problematic in future.
# Current image has docker installed.
# - name: Add Docker apt repository key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

# - name: Add Docker apt repositoy key
#   apt_repository:
#     repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
#     mode: 644
#     update_cache: yes
#     state: present

# - name: Install Docker
#   apt:
#     name: ["docker-ce"]
#     state: latest
#     update_cache: yes
#     install_recommends: no

# - name: Assert Docker is running
#   systemd:
#     name: docker
#     state: started

# - name: Restart Docker
#   systemd:
#     name: docker
#     state: restarted

- name: Restart SSH service.
  import_tasks: restart_ssh.yaml
